# Generated by Django 3.1.1 on 2020-10-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to='media/'),
        ),
    ]
